EQUIPE    E05

COMPONENTES:     
Nome                    Email                                     Telefone
Jander Almeida Silva    jander.silva@aln.senaicimatec.com.br     (71) 99961-6841
Jafe Ferreira           jafe.ferreira@aln.senaicimatec.edu.br    (71) 8815-3915
Ruan Nilton Azevedo     ruan.azevedo@aln.senaicimatec.edu.br     (75) 8334-6684




Entrada|Lexema|Codigo|Qnt|Aparicoes(5)
--------------------------------------
0      |BEGIN |A02   |1  |1           
1      |INT   |A12   |1  |2           
2      |;     |B09   |2  |2,2         
3      |VOID  |A07   |1  |3           
4      |(     |B05   |2  |3,4         
5      |)     |B07   |2  |3,4         
6      |{     |B13   |2  |3,4         
7      |IF    |A13   |1  |4           
8      |==    |B20   |1  |4           
9      |}     |B16   |2  |6,7         
10     |END   |A16   |1  |9           